const DEMAND_STATUS = {
  ABERTA: 'ABERTA',
  TRIAGEM: 'TRIAGEM',
  EM_ANDAMENTO: 'EM_ANDAMENTO',
  AGUARDANDO_ORCAMENTO: 'AGUARDANDO_ORCAMENTO',
  AGUARDANDO_APROVACAO: 'AGUARDANDO_APROVACAO',
  AGENDADA: 'AGENDADA',
  CONCLUIDA: 'CONCLUIDA',
  CANCELADA: 'CANCELADA',
};

const DEMAND_PRIORITY = {
  CRITICA: 'CRITICA',
  ALTA: 'ALTA',
  MEDIA: 'MEDIA',
  BAIXA: 'BAIXA',
};

const DEMAND_CATEGORY = {
  MANUTENCAO: 'MANUTENCAO',
  LIMPEZA: 'LIMPEZA',
  SEGURANCA: 'SEGURANCA',
  FINANCEIRO: 'FINANCEIRO',
  BARULHO: 'BARULHO',
  INFRAESTRUTURA: 'INFRAESTRUTURA',
  ADMINISTRATIVO: 'ADMINISTRATIVO',
  OUTRO: 'OUTRO',
};

module.exports = { DEMAND_STATUS, DEMAND_PRIORITY, DEMAND_CATEGORY };
